[package]
name = "image_crawler"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.11", features = ["json"] }
tokio = { version = "1.0", features = ["full"] }
scraper = "0.18"
url = "2.5"
image = "0.24"
anyhow = "1.0"
futures = "0.3"
